--
local bucket = Inventory.BaseItemObjects.Generic("bucket")
bucket 	:SetName("THE CUM BUCKET")
		:SetModel("models/props_junk/watermelon01.mdl")
		:SetLookAng(Angle(15, 220, 0))
		--:SetCamOffset(Vector(0, 0, -50))
		:SetFOV(5)
		:NetworkVar("Color", "Color")
		:On("SetInSlot", function(base, item, ipnl, imdl)
			imdl:SetColor(item.Data.Color or color_white)
		end)
		:SetCountable(true)
		:SetMaxStack(10)